### ISSUE TITLE
Tipo de Atributos

### ISSUE THREAD

**Issue by andru255** [frontend-labs/style-guide#22]
Mejorar el titulo mas descriptivo
Corregir en los ejemplos los atributos, colocarlos en orden alfabetico. como nuestro style-guide :D 
Colocar un salto de linea entre los ejemplos.

El archivo a editar es:
https://github.com/frontend-labs/style-guide/blob/master/html/tipo-de-atributos.md

**Comment by pakgva** [comment]
@andru255 se realizó la modificación en el siguiente commit [fix(html): Ejemplos acorde a los standares dictados](https://github.com/frontend-labs/style-guide/commit/8a898f45bf6acd41634000b1d97efd1fb79dae27)
